kind: pipeline
name: default

steps:
  - name: build-image
    image: plugins/docker
    settings:
      repo: oreshkin/blocks
      tags: latest
      dockerfile: Dockerfile
      username:
        from_secret: docker_login
      password:
        from_secret: docker_password

trigger:
  branch:
  - master