kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    pull: if-not-exists
    settings:
      repo: oreshkin/blocks
      cache_from: oreshkin/blocks:latest
      tags: latest
      dockerfile: Dockerfile
      username: oreshkin
      password: 3$/yXFtrs9MFN
      target: build-stage
