kind: pipeline
type: docker
name: build

steps:
  - name: build-frontend-image
    pull: if-not-exists
    image: plugins/docker
    settings:
      registry: hub.docker.com
      repo: hub.docker.com/oreshkin/blocks
      tags: latest
      dockerfile: Dockerfile
      username:
        from_secret: docker_login
      password:
        from_secret: docker_password

trigger:
  branch:
  - master